package io.commodity.contracts.refs;

/**
 * Top of the nested reference scheme: trade {@code 1}, its quotas {@code 1.1, 1.2},
 * their assignments {@code 1.1.1, 1.1.2}.
 *
 * <p>Why it exists: the nesting is deliberate (captured requirement). A ref tells you
 * its whole ancestry with no lookup, so support staff, logs and events read naturally.
 * Interview talking point: "human-readable composite keys, generated by plain Java,
 * stored as text".
 *
 * <p>TRADEOFF: text refs sort lexicographically ("1.10" before "1.2"), so any ordering
 * must use {@link #compareTo}, never an SQL ORDER BY on the text. The cost of readable
 * keys is that you must remember this.
 *
 * <p>Lives in :contracts so every service speaks the same ref type without depending on
 * another service. No framework here (project conventions rule 4).
 */
public record TradeRef(long number) implements Comparable<TradeRef> {

    public TradeRef {
        // INVARIANT: refs are 1-based positive numbers (tested in RefsTest).
        if (number < 1) throw new IllegalArgumentException("trade number must be >= 1: " + number);
    }

    /** Parses "12" into a TradeRef. */
    public static TradeRef parse(String text) {
        try {
            return new TradeRef(Long.parseLong(text));
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("not a trade ref: " + text, e);
        }
    }

    /** Child quota ref, e.g. trade 1 + seq 2 = "1.2". */
    public QuotaRef quota(int seq) {
        return new QuotaRef(this, seq);
    }

    @Override
    public int compareTo(TradeRef o) {
        return Long.compare(number, o.number);
    }

    @Override
    public String toString() {
        return Long.toString(number);
    }
}
